timeout: 10m

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/media-streaming-mesh/msm-cp)
  goimports:
    local-prefixes: github.com/media-streaming-mesh/msm-cp

linters:
  disable-all: true
  enable:
    - gofmt
    - gofumpt
    - goimports
    - whitespace

    # FIXME
    # - revive
    # - staticcheck
    # - stylecheck
