//
// Copyright (c) 2022 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: msm_dp.proto

package msm_dp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamOperation int32

const (
	StreamOperation_CREATE StreamOperation = 0
	StreamOperation_UPDATE StreamOperation = 1
	StreamOperation_DELETE StreamOperation = 2
	StreamOperation_ADD_EP StreamOperation = 3
	StreamOperation_DEL_EP StreamOperation = 4
)

// Enum value maps for StreamOperation.
var (
	StreamOperation_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
		3: "ADD_EP",
		4: "DEL_EP",
	}
	StreamOperation_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"DELETE": 2,
		"ADD_EP": 3,
		"DEL_EP": 4,
	}
)

func (x StreamOperation) Enum() *StreamOperation {
	p := new(StreamOperation)
	*p = x
	return p
}

func (x StreamOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_msm_dp_proto_enumTypes[0].Descriptor()
}

func (StreamOperation) Type() protoreflect.EnumType {
	return &file_msm_dp_proto_enumTypes[0]
}

func (x StreamOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamOperation.Descriptor instead.
func (StreamOperation) EnumDescriptor() ([]byte, []int) {
	return file_msm_dp_proto_rawDescGZIP(), []int{0}
}

type RtpEncap int32

const (
	RtpEncap_UDP         RtpEncap = 0
	RtpEncap_UDP_MUXED   RtpEncap = 1
	RtpEncap_TCP         RtpEncap = 2
	RtpEncap_TCP_MUXED   RtpEncap = 3
	RtpEncap_QUIC_STREAM RtpEncap = 4
	RtpEncap_QUIC_DGRAM  RtpEncap = 5
)

// Enum value maps for RtpEncap.
var (
	RtpEncap_name = map[int32]string{
		0: "UDP",
		1: "UDP_MUXED",
		2: "TCP",
		3: "TCP_MUXED",
		4: "QUIC_STREAM",
		5: "QUIC_DGRAM",
	}
	RtpEncap_value = map[string]int32{
		"UDP":         0,
		"UDP_MUXED":   1,
		"TCP":         2,
		"TCP_MUXED":   3,
		"QUIC_STREAM": 4,
		"QUIC_DGRAM":  5,
	}
)

func (x RtpEncap) Enum() *RtpEncap {
	p := new(RtpEncap)
	*p = x
	return p
}

func (x RtpEncap) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RtpEncap) Descriptor() protoreflect.EnumDescriptor {
	return file_msm_dp_proto_enumTypes[1].Descriptor()
}

func (RtpEncap) Type() protoreflect.EnumType {
	return &file_msm_dp_proto_enumTypes[1]
}

func (x RtpEncap) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RtpEncap.Descriptor instead.
func (RtpEncap) EnumDescriptor() ([]byte, []int) {
	return file_msm_dp_proto_rawDescGZIP(), []int{1}
}

type RtpEndpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encap  RtpEncap `protobuf:"varint,1,opt,name=encap,proto3,enum=msm_dp.RtpEncap" json:"encap,omitempty"`
	Source string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Dest   string   `protobuf:"bytes,3,opt,name=dest,proto3" json:"dest,omitempty"`
}

func (x *RtpEndpoint) Reset() {
	*x = RtpEndpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msm_dp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtpEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtpEndpoint) ProtoMessage() {}

func (x *RtpEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_msm_dp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtpEndpoint.ProtoReflect.Descriptor instead.
func (*RtpEndpoint) Descriptor() ([]byte, []int) {
	return file_msm_dp_proto_rawDescGZIP(), []int{0}
}

func (x *RtpEndpoint) GetEncap() RtpEncap {
	if x != nil {
		return x.Encap
	}
	return RtpEncap_UDP
}

func (x *RtpEndpoint) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RtpEndpoint) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

type StreamData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamOperation StreamOperation `protobuf:"varint,1,opt,name=stream_operation,json=streamOperation,proto3,enum=msm_dp.StreamOperation" json:"stream_operation,omitempty"`
	StreamId        uint32          `protobuf:"varint,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	StreamEndpoint  *RtpEndpoint    `protobuf:"bytes,3,opt,name=stream_endpoint,json=streamEndpoint,proto3" json:"stream_endpoint,omitempty"`
}

func (x *StreamData) Reset() {
	*x = StreamData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msm_dp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamData) ProtoMessage() {}

func (x *StreamData) ProtoReflect() protoreflect.Message {
	mi := &file_msm_dp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamData.ProtoReflect.Descriptor instead.
func (*StreamData) Descriptor() ([]byte, []int) {
	return file_msm_dp_proto_rawDescGZIP(), []int{1}
}

func (x *StreamData) GetStreamOperation() StreamOperation {
	if x != nil {
		return x.StreamOperation
	}
	return StreamOperation_CREATE
}

func (x *StreamData) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *StreamData) GetStreamEndpoint() *RtpEndpoint {
	if x != nil {
		return x.StreamEndpoint
	}
	return nil
}

type StreamResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *StreamResult) Reset() {
	*x = StreamResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msm_dp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResult) ProtoMessage() {}

func (x *StreamResult) ProtoReflect() protoreflect.Message {
	mi := &file_msm_dp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResult.ProtoReflect.Descriptor instead.
func (*StreamResult) Descriptor() ([]byte, []int) {
	return file_msm_dp_proto_rawDescGZIP(), []int{2}
}

func (x *StreamResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_msm_dp_proto protoreflect.FileDescriptor

var file_msm_dp_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x73, 0x6d, 0x5f, 0x64, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6d, 0x73, 0x6d, 0x5f, 0x64, 0x70, 0x22, 0x61, 0x0a, 0x0b, 0x52, 0x74, 0x70, 0x45, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x6e, 0x63, 0x61, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6d, 0x73, 0x6d, 0x5f, 0x64, 0x70, 0x2e, 0x52, 0x74,
	0x70, 0x45, 0x6e, 0x63, 0x61, 0x70, 0x52, 0x05, 0x65, 0x6e, 0x63, 0x61, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x74, 0x22, 0xab, 0x01, 0x0a, 0x0a, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x42, 0x0a, 0x10, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6d, 0x73, 0x6d, 0x5f, 0x64, 0x70, 0x2e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x73, 0x6d, 0x5f, 0x64, 0x70, 0x2e, 0x52, 0x74, 0x70, 0x45,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x4d, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x4d, 0x0a, 0x0f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45,
	0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a,
	0x06, 0x41, 0x44, 0x44, 0x5f, 0x45, 0x50, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c,
	0x5f, 0x45, 0x50, 0x10, 0x04, 0x2a, 0x5b, 0x0a, 0x08, 0x52, 0x74, 0x70, 0x45, 0x6e, 0x63, 0x61,
	0x70, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x44, 0x50, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x44,
	0x50, 0x5f, 0x4d, 0x55, 0x58, 0x45, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x43, 0x50,
	0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x43, 0x50, 0x5f, 0x4d, 0x55, 0x58, 0x45, 0x44, 0x10,
	0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x51, 0x55, 0x49, 0x43, 0x5f, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d,
	0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x51, 0x55, 0x49, 0x43, 0x5f, 0x44, 0x47, 0x52, 0x41, 0x4d,
	0x10, 0x05, 0x32, 0x4c, 0x0a, 0x0c, 0x4d, 0x73, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x50, 0x6c, 0x61,
	0x6e, 0x65, 0x12, 0x3c, 0x0a, 0x0e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x61, 0x64, 0x64,
	0x5f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x2e, 0x6d, 0x73, 0x6d, 0x5f, 0x64, 0x70, 0x2e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x14, 0x2e, 0x6d, 0x73, 0x6d, 0x5f, 0x64,
	0x70, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x2d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2d, 0x6d,
	0x65, 0x73, 0x68, 0x2f, 0x6d, 0x73, 0x6d, 0x2d, 0x64, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6d, 0x73, 0x6d, 0x5f, 0x64, 0x70, 0x3b, 0x6d,
	0x73, 0x6d, 0x5f, 0x64, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msm_dp_proto_rawDescOnce sync.Once
	file_msm_dp_proto_rawDescData = file_msm_dp_proto_rawDesc
)

func file_msm_dp_proto_rawDescGZIP() []byte {
	file_msm_dp_proto_rawDescOnce.Do(func() {
		file_msm_dp_proto_rawDescData = protoimpl.X.CompressGZIP(file_msm_dp_proto_rawDescData)
	})
	return file_msm_dp_proto_rawDescData
}

var file_msm_dp_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_msm_dp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_msm_dp_proto_goTypes = []interface{}{
	(StreamOperation)(0), // 0: msm_dp.StreamOperation
	(RtpEncap)(0),        // 1: msm_dp.RtpEncap
	(*RtpEndpoint)(nil),  // 2: msm_dp.RtpEndpoint
	(*StreamData)(nil),   // 3: msm_dp.StreamData
	(*StreamResult)(nil), // 4: msm_dp.StreamResult
}
var file_msm_dp_proto_depIdxs = []int32{
	1, // 0: msm_dp.RtpEndpoint.encap:type_name -> msm_dp.RtpEncap
	0, // 1: msm_dp.StreamData.stream_operation:type_name -> msm_dp.StreamOperation
	2, // 2: msm_dp.StreamData.stream_endpoint:type_name -> msm_dp.RtpEndpoint
	3, // 3: msm_dp.MsmDataPlane.stream_add_del:input_type -> msm_dp.StreamData
	4, // 4: msm_dp.MsmDataPlane.stream_add_del:output_type -> msm_dp.StreamResult
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_msm_dp_proto_init() }
func file_msm_dp_proto_init() {
	if File_msm_dp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msm_dp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtpEndpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msm_dp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msm_dp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msm_dp_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msm_dp_proto_goTypes,
		DependencyIndexes: file_msm_dp_proto_depIdxs,
		EnumInfos:         file_msm_dp_proto_enumTypes,
		MessageInfos:      file_msm_dp_proto_msgTypes,
	}.Build()
	File_msm_dp_proto = out.File
	file_msm_dp_proto_rawDesc = nil
	file_msm_dp_proto_goTypes = nil
	file_msm_dp_proto_depIdxs = nil
}
