//
// Copyright (c) 2022 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: msm_dp.proto

package msm_dp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamOperation int32

const (
	StreamOperation_CREATE StreamOperation = 0
	StreamOperation_UPDATE StreamOperation = 1
	StreamOperation_DELETE StreamOperation = 2
	StreamOperation_ADD_EP StreamOperation = 3
	StreamOperation_DEL_EP StreamOperation = 4
	StreamOperation_UPD_EP StreamOperation = 5
)

// Enum value maps for StreamOperation.
var (
	StreamOperation_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
		3: "ADD_EP",
		4: "DEL_EP",
		5: "UPD_EP",
	}
	StreamOperation_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"DELETE": 2,
		"ADD_EP": 3,
		"DEL_EP": 4,
		"UPD_EP": 5,
	}
)

func (x StreamOperation) Enum() *StreamOperation {
	p := new(StreamOperation)
	*p = x
	return p
}

func (x StreamOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_msm_dp_proto_enumTypes[0].Descriptor()
}

func (StreamOperation) Type() protoreflect.EnumType {
	return &file_msm_dp_proto_enumTypes[0]
}

func (x StreamOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamOperation.Descriptor instead.
func (StreamOperation) EnumDescriptor() ([]byte, []int) {
	return file_msm_dp_proto_rawDescGZIP(), []int{0}
}

type ProxyProtocol int32

const (
	ProxyProtocol_TCP  ProxyProtocol = 0
	ProxyProtocol_UDP  ProxyProtocol = 1
	ProxyProtocol_QUIC ProxyProtocol = 2
	ProxyProtocol_RTP  ProxyProtocol = 3
)

// Enum value maps for ProxyProtocol.
var (
	ProxyProtocol_name = map[int32]string{
		0: "TCP",
		1: "UDP",
		2: "QUIC",
		3: "RTP",
	}
	ProxyProtocol_value = map[string]int32{
		"TCP":  0,
		"UDP":  1,
		"QUIC": 2,
		"RTP":  3,
	}
)

func (x ProxyProtocol) Enum() *ProxyProtocol {
	p := new(ProxyProtocol)
	*p = x
	return p
}

func (x ProxyProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_msm_dp_proto_enumTypes[1].Descriptor()
}

func (ProxyProtocol) Type() protoreflect.EnumType {
	return &file_msm_dp_proto_enumTypes[1]
}

func (x ProxyProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyProtocol.Descriptor instead.
func (ProxyProtocol) EnumDescriptor() ([]byte, []int) {
	return file_msm_dp_proto_rawDescGZIP(), []int{1}
}

type Encap int32

const (
	Encap_TCP_IP          Encap = 0
	Encap_UDP_IP          Encap = 1
	Encap_QUIC_IP         Encap = 2
	Encap_RTP_UDP         Encap = 3
	Encap_RTP_UDP_MUX     Encap = 4
	Encap_RTP_TCP         Encap = 5
	Encap_RTP_TCP_MUX     Encap = 6
	Encap_RTP_QUIC_STREAM Encap = 7
	Encap_RTP_QUIC_DGRAM  Encap = 8
)

// Enum value maps for Encap.
var (
	Encap_name = map[int32]string{
		0: "TCP_IP",
		1: "UDP_IP",
		2: "QUIC_IP",
		3: "RTP_UDP",
		4: "RTP_UDP_MUX",
		5: "RTP_TCP",
		6: "RTP_TCP_MUX",
		7: "RTP_QUIC_STREAM",
		8: "RTP_QUIC_DGRAM",
	}
	Encap_value = map[string]int32{
		"TCP_IP":          0,
		"UDP_IP":          1,
		"QUIC_IP":         2,
		"RTP_UDP":         3,
		"RTP_UDP_MUX":     4,
		"RTP_TCP":         5,
		"RTP_TCP_MUX":     6,
		"RTP_QUIC_STREAM": 7,
		"RTP_QUIC_DGRAM":  8,
	}
)

func (x Encap) Enum() *Encap {
	p := new(Encap)
	*p = x
	return p
}

func (x Encap) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encap) Descriptor() protoreflect.EnumDescriptor {
	return file_msm_dp_proto_enumTypes[2].Descriptor()
}

func (Encap) Type() protoreflect.EnumType {
	return &file_msm_dp_proto_enumTypes[2]
}

func (x Encap) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Encap.Descriptor instead.
func (Encap) EnumDescriptor() ([]byte, []int) {
	return file_msm_dp_proto_rawDescGZIP(), []int{2}
}

type Endpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceIp   string `protobuf:"bytes,1,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	DestIp     string `protobuf:"bytes,2,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	SourcePort uint32 `protobuf:"varint,3,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestPort   uint32 `protobuf:"varint,4,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	QuicStream uint64 `protobuf:"varint,5,opt,name=quic_stream,json=quicStream,proto3" json:"quic_stream,omitempty"`
	Encap      Encap  `protobuf:"varint,6,opt,name=encap,proto3,enum=msm_dp.Encap" json:"encap,omitempty"`
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msm_dp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_msm_dp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_msm_dp_proto_rawDescGZIP(), []int{0}
}

func (x *Endpoint) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *Endpoint) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *Endpoint) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *Endpoint) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *Endpoint) GetQuicStream() uint64 {
	if x != nil {
		return x.QuicStream
	}
	return 0
}

func (x *Endpoint) GetEncap() Encap {
	if x != nil {
		return x.Encap
	}
	return Encap_TCP_IP
}

type StreamData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Operation StreamOperation `protobuf:"varint,2,opt,name=operation,proto3,enum=msm_dp.StreamOperation" json:"operation,omitempty"`
	Protocol  ProxyProtocol   `protobuf:"varint,3,opt,name=protocol,proto3,enum=msm_dp.ProxyProtocol" json:"protocol,omitempty"`
	Endpoint  *Endpoint       `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Enable    bool            `protobuf:"varint,5,opt,name=enable,proto3" json:"enable,omitempty"`
}

func (x *StreamData) Reset() {
	*x = StreamData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msm_dp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamData) ProtoMessage() {}

func (x *StreamData) ProtoReflect() protoreflect.Message {
	mi := &file_msm_dp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamData.ProtoReflect.Descriptor instead.
func (*StreamData) Descriptor() ([]byte, []int) {
	return file_msm_dp_proto_rawDescGZIP(), []int{1}
}

func (x *StreamData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StreamData) GetOperation() StreamOperation {
	if x != nil {
		return x.Operation
	}
	return StreamOperation_CREATE
}

func (x *StreamData) GetProtocol() ProxyProtocol {
	if x != nil {
		return x.Protocol
	}
	return ProxyProtocol_TCP
}

func (x *StreamData) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *StreamData) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type StreamResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *StreamResult) Reset() {
	*x = StreamResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msm_dp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResult) ProtoMessage() {}

func (x *StreamResult) ProtoReflect() protoreflect.Message {
	mi := &file_msm_dp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResult.ProtoReflect.Descriptor instead.
func (*StreamResult) Descriptor() ([]byte, []int) {
	return file_msm_dp_proto_rawDescGZIP(), []int{2}
}

func (x *StreamResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_msm_dp_proto protoreflect.FileDescriptor

var file_msm_dp_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x73, 0x6d, 0x5f, 0x64, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6d, 0x73, 0x6d, 0x5f, 0x64, 0x70, 0x22, 0xc4, 0x01, 0x0a, 0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x70,
	0x12, 0x17, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65,
	0x73, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64,
	0x65, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x69, 0x63, 0x5f,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x71, 0x75,
	0x69, 0x63, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x23, 0x0a, 0x05, 0x65, 0x6e, 0x63, 0x61,
	0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x6d, 0x5f, 0x64, 0x70,
	0x2e, 0x45, 0x6e, 0x63, 0x61, 0x70, 0x52, 0x05, 0x65, 0x6e, 0x63, 0x61, 0x70, 0x22, 0xcc, 0x01,
	0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x09,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x17, 0x2e, 0x6d, 0x73, 0x6d, 0x5f, 0x64, 0x70, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6d, 0x73, 0x6d, 0x5f, 0x64, 0x70, 0x2e, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x2c, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x73, 0x6d, 0x5f, 0x64,
	0x70, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x4d, 0x0a, 0x0c,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x59, 0x0a, 0x0f, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a,
	0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50,
	0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x44, 0x44, 0x5f, 0x45, 0x50, 0x10, 0x03, 0x12, 0x0a,
	0x0a, 0x06, 0x44, 0x45, 0x4c, 0x5f, 0x45, 0x50, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50,
	0x44, 0x5f, 0x45, 0x50, 0x10, 0x05, 0x2a, 0x34, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x43, 0x50, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x55, 0x44, 0x50, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x51, 0x55, 0x49,
	0x43, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x54, 0x50, 0x10, 0x03, 0x2a, 0x91, 0x01, 0x0a,
	0x05, 0x45, 0x6e, 0x63, 0x61, 0x70, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x43, 0x50, 0x5f, 0x49, 0x50,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x44, 0x50, 0x5f, 0x49, 0x50, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x51, 0x55, 0x49, 0x43, 0x5f, 0x49, 0x50, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x52,
	0x54, 0x50, 0x5f, 0x55, 0x44, 0x50, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x54, 0x50, 0x5f,
	0x55, 0x44, 0x50, 0x5f, 0x4d, 0x55, 0x58, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x54, 0x50,
	0x5f, 0x54, 0x43, 0x50, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x54, 0x50, 0x5f, 0x54, 0x43,
	0x50, 0x5f, 0x4d, 0x55, 0x58, 0x10, 0x06, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x54, 0x50, 0x5f, 0x51,
	0x55, 0x49, 0x43, 0x5f, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x10, 0x07, 0x12, 0x12, 0x0a, 0x0e,
	0x52, 0x54, 0x50, 0x5f, 0x51, 0x55, 0x49, 0x43, 0x5f, 0x44, 0x47, 0x52, 0x41, 0x4d, 0x10, 0x08,
	0x32, 0x4c, 0x0a, 0x0c, 0x4d, 0x73, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x50, 0x6c, 0x61, 0x6e, 0x65,
	0x12, 0x3c, 0x0a, 0x0e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x61, 0x64, 0x64, 0x5f, 0x64,
	0x65, 0x6c, 0x12, 0x12, 0x2e, 0x6d, 0x73, 0x6d, 0x5f, 0x64, 0x70, 0x2e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x14, 0x2e, 0x6d, 0x73, 0x6d, 0x5f, 0x64, 0x70, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x43,
	0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x2d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2d, 0x6d, 0x65, 0x73,
	0x68, 0x2f, 0x6d, 0x73, 0x6d, 0x2d, 0x64, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6d, 0x73, 0x6d, 0x5f, 0x64, 0x70, 0x3b, 0x6d, 0x73, 0x6d,
	0x5f, 0x64, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msm_dp_proto_rawDescOnce sync.Once
	file_msm_dp_proto_rawDescData = file_msm_dp_proto_rawDesc
)

func file_msm_dp_proto_rawDescGZIP() []byte {
	file_msm_dp_proto_rawDescOnce.Do(func() {
		file_msm_dp_proto_rawDescData = protoimpl.X.CompressGZIP(file_msm_dp_proto_rawDescData)
	})
	return file_msm_dp_proto_rawDescData
}

var file_msm_dp_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_msm_dp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_msm_dp_proto_goTypes = []interface{}{
	(StreamOperation)(0), // 0: msm_dp.StreamOperation
	(ProxyProtocol)(0),   // 1: msm_dp.ProxyProtocol
	(Encap)(0),           // 2: msm_dp.Encap
	(*Endpoint)(nil),     // 3: msm_dp.Endpoint
	(*StreamData)(nil),   // 4: msm_dp.StreamData
	(*StreamResult)(nil), // 5: msm_dp.StreamResult
}
var file_msm_dp_proto_depIdxs = []int32{
	2, // 0: msm_dp.Endpoint.encap:type_name -> msm_dp.Encap
	0, // 1: msm_dp.StreamData.operation:type_name -> msm_dp.StreamOperation
	1, // 2: msm_dp.StreamData.protocol:type_name -> msm_dp.ProxyProtocol
	3, // 3: msm_dp.StreamData.endpoint:type_name -> msm_dp.Endpoint
	4, // 4: msm_dp.MsmDataPlane.stream_add_del:input_type -> msm_dp.StreamData
	5, // 5: msm_dp.MsmDataPlane.stream_add_del:output_type -> msm_dp.StreamResult
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_msm_dp_proto_init() }
func file_msm_dp_proto_init() {
	if File_msm_dp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msm_dp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Endpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msm_dp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msm_dp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msm_dp_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msm_dp_proto_goTypes,
		DependencyIndexes: file_msm_dp_proto_depIdxs,
		EnumInfos:         file_msm_dp_proto_enumTypes,
		MessageInfos:      file_msm_dp_proto_msgTypes,
	}.Build()
	File_msm_dp_proto = out.File
	file_msm_dp_proto_rawDesc = nil
	file_msm_dp_proto_goTypes = nil
	file_msm_dp_proto_depIdxs = nil
}
